### PR TITLE
Make dirty files unique per source file

### PR DESCRIPTION
**Pull request by RSDuck**
Apparently nimsuggest assumes this to be true and not doing can result in this: https://github.com/pragmagic/vscode-nim/issues/180

### CODE REVIEW

**Comment by saem** [comment]
I read through the linked ticket, I think this would create lots of dirty files and we wouldn't have a particularly great way of knowing if we can clean them up.

Not an entire solution, but perhaps using the nimsuggest process pid as the discriminant tracked as a separate field as part of `NimSuggestProcessDescription` would be the right way to go? Even without being perfect (I'm ok with reasonable effort) the dirty files can be deleted on shutdown or detected crash of the associated nimsuggest process.

Thoughts?

**Comment by RSDuck** [comment]
I agree, I'll group them into an folder per nimsuggest instance and add some clean up code so that the files don't pile up.

**Comment by RSDuck** [comment]
that's done now.

On a side note, I try to be consistent with style, though I've already made an issue about code formatting and I wonder what's the best way to go about this. There are also some other things which nimpretty doesn't change like grouping multiple variables inside one var block, which I know not everybody does (but I adore this syntax 😄), shall I just create a PRs for this and a few other things?

**Comment by saem** [comment]
Looks good to me, thanks!

For the formatting, I think the only thing I care about is 80 char line width, as it lets me have many sources files open side by side on my wide screen -- but I've broken that rule plenty. This was definitely a "figure out Nim as I go" project and so I'm not wedded to the current formatting or much else for that matter, I'll happily accept a PR.

**Comment by saem** [comment]
FYI, I'm working on a release at the moment, new version should be out soon.

**Comment by JorySchossau** [comment]
@RSDuck Yay! Thanks. Our dev team thanks you, too.

**Pull request merged**
