### PR TITLE
redo changes from #86/#90

### PR DESCRIPTION
**Pull request by morganholly**
this was easier than trying to rebase

### CODE REVIEW

**Comment by RSDuck** [comment]
I forgot that last time, but `of` is an binary operator too 😄.

https://nim-lang.org/docs/manual.html#types-tuples-and-object-types

**Comment by morganholly** [comment]
oops. well i’ll work on the regex some more later today. i have an idea of how it will work, hopefully it’s right.

**Comment by morganholly** [comment]
@RSDuck is it possible to put a case expression in an if/when/elif? it seems to not work, i'm getting errors from the extension, but if it does the regex i came up with wouldn't work there.

**Comment by morganholly** [comment]
oh im going to have to create a new PR right, i was confused when my commit didn't show up here

**Comment by RSDuck** [comment]
> @RSDuck is it possible to put a case expression in an if/when/elif? it seems to not work, i'm getting errors from the extension, but if it does the regex i came up with wouldn't work there.

yes it's possible like this:

```nim
if (case range[0..1](1)
    of 0: false
    of 1: true):
  echo "miauz"
```

**Comment by morganholly** [comment]
does it require the parens?

**Comment by RSDuck** [comment]
I think yes, I cannot get it to work without them, though I'm not 100% sure.

**Comment by saem** [comment]
Not at my computer, but I'm pretty sure it'dt be possible to do similar things in a bracket expression that evaluates to an array index for lookup.

Basically the nesting could be achieved in a few ways.

**Pull request merged**
